# Dockerize & deploy to Heroku specific tag
name: prod-man-workflow

on:
  workflow_dispatch: # To trigger manually
    inputs:
      version:
        description: Tag Version
        default: v0.0.1
        required: true
env:
  STAGE: prod

jobs:
  dockerize:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        ref: ${{ github.event.inputs.version }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          stack: container
          branch: "main"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}-${{env.STAGE}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: "web"
          dontautocreate: true
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}-${{env.STAGE}}.herokuapp.com/health"
          checkstring: "OK.STAGE:${{env.STAGE}}"
          delay: 5
          rollbackonhealthcheckfailed: true
